DrugStore/Models/Entities/Drug.cs
using DrugStore.Models.Base;
using System;
using System.Data.SqlTypes;

namespace DrugStore.Models.Entities
{
    public class Drug : BaseEntity<int>
    {
        public string Name { get; set; }
        public string Manufacturer { get; set; } //производитель
        public decimal _price;
        public decimal Price
        {
            get
            {
                return _price;
            }

            set
            {
                if (value > 0)
                {
                    _price = value;
                }
                else
                {
                    _price = 0;
                }
            }
        }

        //public decimal _quantityForSale;
        //public decimal QuantityForSale
        //{
        //    get
        //    {
        //        return _quantityForSale;
        //    }

        //    set
        //    {
        //        if (value > 0)
        //        {
        //            _quantityForSale = value;
        //        }
        //        else
        //        {
        //            _quantityForSale = 0;
        //        }
        //    }
        //}

        public string Batch { get; set; } // серия препарата
        public DateTime ShelfLife { get; set; }
        public double InStock { get; set; }
        public Drug() {
            Name = "";
            Manufacturer = "";
            Price = 0;
            Batch = "";
            ShelfLife = new DateTime();
            InStock = 0;
             }

        //public IEnumerator GetEnumerator()
        //{
        //    return ListDrugs.GetEnumerator();
        //}


        /*  public List<Drug> ListDrugs { get; set; }
          public Drug()
          {
              ListDrugs = new List<Drug>();
          }
        */


    }
}

DrugStore/Controllers/DrugsController.cs
using DrugStore.Models.Database;
using DrugStore.Models.Entities;
using System;
using System.Collections.Generic;
using System.Data.Entity;
using System.Linq;
using System.Net;
using System.Web;
using System.Web.Mvc;
using Excel = Microsoft.Office.Interop.Excel;
using System.Data.SqlTypes;
using System.Data;
using System.IO;
using System.Web.UI;
using System.Web.UI.WebControls;
using ClosedXML.Excel;

namespace DrugStore.Controllers
{
    [Authorize]
    public class DrugsController : Controller
    {
        // GET: Drugs
        // IXLWorksheet worksheet;
        public DrugContext db = new DrugContext();
      
        // GET: Drugs
        public ActionResult Index()
        {
            return View(db.Drugs.ToList());
        }

        // GET: Drugs/Details/5
        public ActionResult Details(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Drug drug = db.Drugs.Find(id);
            if (drug == null)
            {
                return HttpNotFound();
            }
            return View(drug);
        }

        // GET: Drugs/Create
        public ActionResult Create()
        {
            return View();
        }

        // POST: Drugs/Create
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Create([Bind(Include = "Id,Name,Manufacturer,Price,Batch,ShelfLife,InStock")] Drug drug)
        {
            if (ModelState.IsValid)
            {
                db.Drugs.Add(drug);
                db.SaveChanges();
                return RedirectToAction("Index");
            }

            return View(drug);
        }

        // GET: Drugs/Edit/5
        public ActionResult Edit(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Drug drug = db.Drugs.Find(id);
            if (drug == null)
            {
                return HttpNotFound();
            }
            return View(drug);
        }

        // POST: Drugs/Edit/5
        // To protect from overposting attacks, enable the specific properties you want to bind to, for 
        // more details see https://go.microsoft.com/fwlink/?LinkId=317598.
        [HttpPost]
        [ValidateAntiForgeryToken]
        public ActionResult Edit([Bind(Include = "Id,Name,Manufacturer,Price,Batch,ShelfLife,InStock")] Drug drug)
        {
            if (ModelState.IsValid)
            {
                db.Entry(drug).State = EntityState.Modified;
                db.SaveChanges();
                return RedirectToAction("Index");
            }
            return View(drug);
        }

        // GET: Drugs/Delete/5
        public ActionResult Delete(int? id)
        {
            if (id == null)
            {
                return new HttpStatusCodeResult(HttpStatusCode.BadRequest);
            }
            Drug drug = db.Drugs.Find(id);
            if (drug == null)
            {
                return HttpNotFound();
            }
            return View(drug);
        }

        // POST: Drugs/Delete/5
        [HttpPost, ActionName("Delete")]
        [ValidateAntiForgeryToken]
        public ActionResult DeleteConfirmed(int id)
        {
            Drug drug = db.Drugs.Find(id);
            db.Drugs.Remove(drug);
            db.SaveChanges();
            return RedirectToAction("Index");
        }

        protected override void Dispose(bool disposing)
        {
            if (disposing)
            {
                db.Dispose();
            }
            base.Dispose(disposing);
        }

        //[HttpPost]
        //public ActionResult Import(HttpPostedFileBase fileExcel)
        //{
        //    Drug drug = new Drug();
        //    if (ModelState.IsValid)
        //    {

        //       // IXLWorksheet worksheet;
        //        using (XLWorkbook workBook = new XLWorkbook(fileExcel.InputStream, XLEventTracking.Disabled))
        //        {

        //            var worksheet = workBook.Worksheet(1);
        //            //foreach (IXLWorksheet worksheet in workBook.Worksheets)
        //            //{
        //            //    PhoneBrand phoneBrand = new PhoneBrand();
        //            //    phoneBrand.Title = worksheet.Name;

        //            foreach (IXLColumn column in worksheet.ColumnsUsed())
        //            {

        //                //    PhoneModel phoneModel = new PhoneModel();
        //                //    phoneModel.Title = column.Cell(1).Value.ToString();

        //                foreach (IXLRow row in worksheet.RowsUsed().Skip(1))
        //                    {
        //                        try
        //                        {
        //                    ///PricePosition pricePosition = new PricePosition();
        //                    //pricePosition.Problem = row.Cell(1).Value.ToString();
        //                    //pricePosition.Price = row.Cell(column.ColumnNumber()).Value.ToString();
        //                    //phoneModel.PricePositions.Add(pricePosition);

        //                        drug.Name = row.Cell(1).Value.ToString(); 
        //                        drug.Manufacturer = row.Cell(2).Value.ToString();
        //                        drug.Price = (decimal)row.Cell(3).Value;
        //                        drug.Batch = row.Cell(4).Value.ToString();
        //                        drug.ShelfLife = (DateTime)row.Cell(5).Value;
        //                        drug.InStock = (float)row.Cell(6).Value;

        //                        db.Drugs.Add(drug);
        //                    }
        //                        catch (Exception)
        //                        {
        //                            //logging
        //                           // drug.ErrorsTotal++;
        //                        }
        //                   // db.Drugs.Add(drug);
        //                }

        //                // phoneBrand.PhoneModels.Add(phoneModel);
        //                // }
        //              //  db.Drugs.Add(drug);
        //             //  db.Drugs.ToList();

        //            }

        //        }
        //        //например, здесь сохраняем все позиции из прайса в БД

        //     return View(drug);
        //    }

        //     return RedirectToAction("Index");
        //}


        [HttpPost]
        public ActionResult Import(HttpPostedFileBase excelfile)
        {
          
            if (excelfile == null || excelfile.ContentLength == 0)
            {
                ViewBag.Error = "Please select a Excel file.<br>";
                return View("Index");
            }
            else
            {
                if (excelfile.FileName.EndsWith("xls") || excelfile.FileName.EndsWith("xlsx"))
                {
                    string path = Server.MapPath("~/Content/" + excelfile.FileName);
                    //if (System.IO.File.Exists(path))
                    //    System.IO.File.Delete(path);
                    //excelfile.SaveAs(path);
                    Excel.Application application = new Excel.Application();
                    Excel.Workbook workbook = application.Workbooks.Open(path);
                    Excel.Worksheet worksheet = workbook.ActiveSheet;
                    Excel.Range range = worksheet.UsedRange;
                    List<Drug> drugs = new List<Drug>();
                    for (int row = 2; row <= 43; row++)
                    {
                        Drug d = new Drug();
                        d.Id = Convert.ToInt32(((Excel.Range)range.Cells[row, 1]).Value);
                        d.Name = ((Excel.Range)range.Cells[row, 2]).Text;
                        d.Manufacturer = ((Excel.Range)range.Cells[row, 3]).Text;
                        d.Price = Convert.ToDecimal(((Excel.Range)range.Cells[row, 4]).Value);
                        d.Batch = ((Excel.Range)range.Cells[row, 5]).Text;
                        d.ShelfLife = Convert.ToDateTime(((Excel.Range)range.Cells[row, 6]).Value);
                        d.InStock = Convert.ToDouble(((Excel.Range)range.Cells[row, 7]).Value);
                        drugs.Add(d);
                        db.Drugs.Add(d);
                        db.SaveChanges();
                    }
                  
                    ViewBag.drugs = drugs;
                   
                    return View("Import");
                }
                else
                {
                    ViewBag.Error = "File type is incorrect.<br>";
                    return View("Index");
                }
              
            }
           
        }
        


        [HttpPost]
        public FileResult Export()
        {

            DataTable dt = new DataTable("Grid");
            dt.Columns.AddRange(new DataColumn[7] { new DataColumn("Id"),
                                                     new DataColumn("Name"),
                                                     new DataColumn("Manufacturer"),
                                                     new DataColumn("Price"),
                                                     new DataColumn("Batch"),
                                                     new DataColumn("ShelfLife"),
                                                     new DataColumn("InStock") });
                    

            var drug = from Drug in db.Drugs select Drug;

            foreach (var d in drug)
            {
                dt.Rows.Add(d.Id, d.Name, d.Manufacturer, d.Price,
                    d.Batch, d.ShelfLife, d.InStock);
            }

            using (XLWorkbook wb = new XLWorkbook()) //Install ClosedXml from Nuget for XLWorkbook  
            {
                wb.Worksheets.Add(dt);

DrugStore/Views/Drugs/Create.cshtml
@model DrugStore.Models.Entities.Drug

@{
    ViewBag.Title = "Create";
}

<h2>Create</h2>

@using (Html.BeginForm()) 
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Drug</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Manufacturer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Manufacturer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Manufacturer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Batch, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Batch, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Batch, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShelfLife, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShelfLife, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShelfLife, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InStock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InStock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InStock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Create" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DrugStore/Views/Drugs/Delete.cshtml
@model DrugStore.Models.Entities.Drug

@{
    ViewBag.Title = "Delete";
}

<h2>Delete</h2>

<h3>Are you sure you want to delete this?</h3>
<div>
    <h4>Drug</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Manufacturer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Manufacturer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Batch)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Batch)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShelfLife)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShelfLife)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InStock)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InStock)
        </dd>

    </dl>

    @using (Html.BeginForm()) {
        @Html.AntiForgeryToken()

        <div class="form-actions no-color">
            <input type="submit" value="Delete" class="btn btn-default" /> |
            @Html.ActionLink("Back to List", "Index")
        </div>
    }
</div>

DrugStore/Views/Drugs/Details.cshtml
@model DrugStore.Models.Entities.Drug

@{
    ViewBag.Title = "Корзина";
    //int quantity = 1;
}


<h2>Корзина покупок</h2>

<div>
    <h4>Drug</h4>
    <hr />
    <dl class="dl-horizontal">
        <dt>
            @Html.DisplayNameFor(model => model.Name)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Name)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Manufacturer)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Manufacturer)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Price)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Price)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.Batch)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.Batch)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.ShelfLife)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.ShelfLife)
        </dd>

        <dt>
            @Html.DisplayNameFor(model => model.InStock)
        </dt>

        <dd>
            @Html.DisplayFor(model => model.InStock)
        </dd>

    </dl>
</div>


<div class="item">

    @using (Html.BeginForm("AddToCart", "Cart", new { id = Model.Id}))
    {
        @Html.HiddenFor(x => x.Name)
        @Html.Hidden("returnUrl", Request.Url.PathAndQuery)
        
        <input type="submit" class="btn btn-success" value="Добавить в корзину" />
    }

    <h4>@Model.Price.ToString("c")</h4>
</div>
<p>
    @Html.ActionLink("Back to List", "Index")
</p>

DrugStore/Views/Drugs/Edit.cshtml
@model DrugStore.Models.Entities.Drug

@{
    ViewBag.Title = "Edit";
}

<h2>Edit</h2>

@using (Html.BeginForm())
{
    @Html.AntiForgeryToken()
    
    <div class="form-horizontal">
        <h4>Drug</h4>
        <hr />
        @Html.ValidationSummary(true, "", new { @class = "text-danger" })
        @Html.HiddenFor(model => model.Id)

        <div class="form-group">
            @Html.LabelFor(model => model.Name, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Name, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Name, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Manufacturer, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Manufacturer, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Manufacturer, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Price, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Price, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Price, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.Batch, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.Batch, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.Batch, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.ShelfLife, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.ShelfLife, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.ShelfLife, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            @Html.LabelFor(model => model.InStock, htmlAttributes: new { @class = "control-label col-md-2" })
            <div class="col-md-10">
                @Html.EditorFor(model => model.InStock, new { htmlAttributes = new { @class = "form-control" } })
                @Html.ValidationMessageFor(model => model.InStock, "", new { @class = "text-danger" })
            </div>
        </div>

        <div class="form-group">
            <div class="col-md-offset-2 col-md-10">
                <input type="submit" value="Save" class="btn btn-default" />
            </div>
        </div>
    </div>
}

<div>
    @Html.ActionLink("Back to List", "Index")
</div>

DrugStore/Views/Drugs/Import.cshtml
@using DrugStore.Models.Entities
@model Drug

@*@model IEnumerable<Pharmacy.Models.Drug>*@

@{
    ViewBag.Title = "Import";
    // Layout = "~/Views/Drugs/Index.cshtml";
}

<h2>List Drugs</h2>

@*<table class="table">
        <tr>
            <th>
                @Html.DisplayNameFor(model => model.Name)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Manufacturer)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Price)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.Batch)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.ShelfLife)
            </th>
            <th>
                @Html.DisplayNameFor(model => model.InStock)
            </th>
            <th></th>
        </tr>

        @for (var item=0; item < 42; item++)
        {
            <tr>
                <td>
                     item.Name
                </td>
                <td>
                    item.Manufacturer
                </td>
                <td>
                    item.Price
                </td>
                <td>
                    item.Batch
                </td>
                <td>
                    item.ShelfLife
                </td>
                <td>
                    item.InStock
                </td>
                <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>
            </tr>
        }

    </table>*@

<table class="pharmacy" border=0>
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Id)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Manufacturer)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Batch)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShelfLife)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.InStock)
        </th>
    </tr>
    @foreach (var item in ViewBag.drugs)
    {
        <tr>
            <td>@item.Id</td>
            <td>@item.Name</td>
            <td>@item.Manufacturer</td>
            <td>@item.Price</td>
            <td>@item.Batch</td>
            <td>@item.ShelfLife</td>
            <td>@item.InStock</td>
            @* <td>
                    @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                    @Html.ActionLink("Details", "Details", new { id = item.Id }) |
                    @Html.ActionLink("Delete", "Delete", new { id = item.Id })
                </td>*@
        </tr>
    }

</table>
<p>
@Html.ActionLink("Back to List", "Index")
</p>

@*<div class="pharmacy">
    <div class="drugs">
        @foreach (var item in ViewBag.drugs)
        {
             <span >@item.Id </span>
            <div>@item.Name </div>
            <div>@item.Manufacturer </div>
            <div>@item.Price </div>
             <span >@item.Batch </span>
             <span >@item.ShelfLife </span>
            <div>@item.InStock </div>

        }
    </div>

    </div>*@

DrugStore/Views/Drugs/Index.cshtml
@model IEnumerable<DrugStore.Models.Entities.Drug>

@{
    ViewBag.Title = "Index";
}

<h2>Database drugs</h2>
<p>&nbsp;</p>
<h3>Импорт файла Excel</h3>
<div>
    @using (Html.BeginForm("Import", "Drugs", FormMethod.Post, new { enctype = "multipart/form-data", id = "frm-excel" }))
    {
        <div>
            Загрузите Excel-файл:
            <input type="file" name="excelfile" id="excelfile" />
            <p></p>
            <div>
                <input type="submit" value="Загрузить" class="btn-success" />
            </div>

        </div>
    }
</div>
<p>&nbsp;</p>
<p>
    @Html.ActionLink("Create New", "Create")
</p>
<table class="table">
    <tr>
        <th>
            @Html.DisplayNameFor(model => model.Name)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Manufacturer)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Price)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.Batch)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.ShelfLife)
        </th>
        <th>
            @Html.DisplayNameFor(model => model.InStock)
        </th>
        <th></th>
    </tr>

    @foreach (var item in Model)
    {
        <tr>
            <td>
                @Html.DisplayFor(modelItem => item.Name)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Manufacturer)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Price)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.Batch)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.ShelfLife)
            </td>
            <td>
                @Html.DisplayFor(modelItem => item.InStock)
            </td>
            <td>
                @Html.ActionLink("Edit", "Edit", new { id = item.Id }) |
                @Html.ActionLink("Выбрать препарат", "Details", new { id = item.Id }) |
                @Html.ActionLink("Delete", "Delete", new { id = item.Id })
            </td>
        </tr>
    }

</table>

<h3>Экспорт файла Excel</h3>
<div>
    @using (Html.BeginForm("Export", "Drugs", FormMethod.Post, new { enctype = "multipart/form-data" }))
    {

        <div>
            <input type="submit" value="Export" class="btn-primary" />
        </div>

    }
</div>  